# Generated by Django 4.2.30 on 2026-09-05 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("signup", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SALES_REP", "Sales Representative"),
                            ("SALES_MANAGER", "Sales Manager / Approver"),
                            ("FINANCE", "Finance / Operations"),
                            ("ADMIN", "Admin"),
                            ("CUSTOMER", "Customer"),
                        ],
                        db_index=True,
                        default="CUSTOMER",
                        max_length=50,
                    ),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                ("company", models.CharField(blank=True, default="", max_length=128)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "ordering": ["-created_at"],
            },
        ),
    ]
