# Generated by Django 4.2.30 on 2026-09-05 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sales", "0002_remove_quotation_idx_quote_customer_created_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DealAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("STALLED_DEAL", "Stalled Deal"),
                            ("HIGH_DISCOUNT_RISK", "High Discount Risk"),
                            ("MARGIN_EROSION", "Margin Erosion"),
                            ("UNUSUAL_VOLUME", "Unusual Volume"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=15,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("details", models.TextField(blank=True, default="")),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_alerts",
                        to="sales.quotation",
                    ),
                ),
            ],
            options={
                "db_table": "deal_alerts",
                "ordering": ["-created_at"],
            },
        ),
    ]
