# Generated by Django 4.2.30 on 2026-09-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_category_pricelist_product_cost_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="pricelist",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
