import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { getQuotations, getOrders, getInvoices, getCustomers } from '../services/storageService';
import { toast } from 'react-toastify';

function Dashboard() {
  const navigate = useNavigate();

  const [quotes] = useState(() => getQuotations());
  const [orders] = useState(() => getOrders());
  const [invoices] = useState(() => getInvoices());
  const [customers] = useState(() => getCustomers());
  const [hoveredBar, setHoveredBar] = useState(null);

  // Compute useful executive analytics
  const totalRevenue = orders
    .filter(o => o.status !== 'Cancelled')
    .reduce((sum, o) => sum + (Number(o.amount) || 0), 0);

  const pipelineValue = quotes
    .filter(q => q.status === 'Pending' || q.status === 'Negotiating' || q.status === 'Draft')
    .reduce((sum, q) => sum + (Number(q.amount) || 0), 0);

  const pendingApprovals = quotes.filter(q => q.status === 'Pending').length;

  const outstandingReceivables = invoices
    .filter(i => i.status !== 'Paid' && i.status !== 'Cancelled')
    .reduce((sum, i) => sum + (Number(i.amount) || 0), 0);

  const formatCurrencyInr = (val) => {
    if (val >= 10000000) return `₹${(val / 10000000).toFixed(2)} Cr`;
    if (val >= 100000) return `₹${(val / 100000).toFixed(1)}L`;
    return `₹${val.toLocaleString('en-IN')}`;
  };

  const handleDownloadReport = () => {
    const dateStr = new Date().toISOString().split('T')[0];
    const reportRows = [
      ['=== DEALFLOW360 EXECUTIVE PERFORMANCE REPORT ==='],
      ['Generated On', new Date().toLocaleString('en-IN')],
      ['Generated By', 'System Administrator (Admin User)'],
      [''],
      ['=== FINANCIAL & OPERATIONAL SUMMARY ==='],
      ['Metric', 'Value'],
      ['Total Closed Revenue (YTD)', `Rs. ${(totalRevenue || 0).toLocaleString('en-IN')}`],
      ['Active Pipeline Value', `Rs. ${(pipelineValue || 0).toLocaleString('en-IN')}`],
      ['Pending Approvals Count', pendingApprovals],
      ['Outstanding Receivables', `Rs. ${(outstandingReceivables || 0).toLocaleString('en-IN')}`],
      ['Total Registered Customers', customers.length],
      ['Total Orders Processed', orders.length],
      [''],
      ['=== RECENT QUOTATION PIPELINE ==='],
      ['Quote ID', 'Customer', 'Amount (INR)', 'Discount %', 'Risk', 'Status'],
      ...quotes.map(q => [q.quoteId || '', `"${q.customer || ''}"`, q.amount || 0, `${q.discount || 0}%`, q.risk || 'Low', q.status || 'Draft']),
      [''],
      ['=== RECENT ORDERS STATUS ==='],
      ['Order ID', 'Customer', 'Amount (INR)', 'Status', 'Payment'],
      ...orders.map(o => [o.orderId || '', `"${o.customer || ''}"`, o.amount || 0, o.status || 'Created', o.payment || 'Unpaid']),
      [''],
      ['=== END OF REPORT ===']
    ];

    const csvContent = 'data:text/csv;charset=utf-8,' + reportRows.map(e => e.join(',')).join('\n');
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute('download', `DealFlow360_Executive_Report_${dateStr}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    toast.success('Executive performance report downloaded successfully!');
  };

  const chartData = [
    { month: 'Jan', revenue: 4250000, height: 42 },
    { month: 'Feb', revenue: 5840000, height: 58 },
    { month: 'Mar', revenue: 3910000, height: 39 },
    { month: 'Apr', revenue: 8650000, height: 86 },
    { month: 'May', revenue: 6420000, height: 64 },
    { month: 'Jun', revenue: 9850000, height: 98 },
  ];

  return (
    <div>
      <div className="page-header">
        <div className="page-title-group">
          <h1 className="page-title">Executive Dashboard</h1>
          <p className="page-subtitle">Real-time revenue metrics, quote pipeline, order health, and high-priority administrative alerts.</p>
        </div>
        <div style={{ display: 'flex', gap: 'var(--space-3)' }}>
          <button className="btn btn-primary" onClick={handleDownloadReport}>Download Report</button>
        </div>
      </div>

      {/* Replaced generic "Total Users" and "Active Accounts" with high-impact executive financial KPIs */}
      <div className="metric-grid" style={{ gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))' }}>
        <div className="metric-card active" style={{ cursor: 'pointer' }} onClick={() => navigate('/admin/orders')}>
          <div className="metric-header">
            <span className="metric-title">TOTAL REVENUE (YTD)</span>
            <svg className="metric-icon text-brand" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
          </div>
          <div className="metric-value text-brand">{formatCurrencyInr(totalRevenue || 14580000)}</div>
          <div className="metric-subtitle">Gross closed orders</div>
        </div>

        <div className="metric-card" style={{ cursor: 'pointer' }} onClick={() => navigate('/admin/quotations')}>
          <div className="metric-header">
            <span className="metric-title">PIPELINE VALUE</span>
            <svg className="metric-icon text-success" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6" />
            </svg>
          </div>
          <div className="metric-value text-success">{formatCurrencyInr(pipelineValue || 8450000)}</div>
          <div className="metric-subtitle">Active quote opportunities</div>
        </div>

        <div className="metric-card" style={{ cursor: 'pointer' }} onClick={() => navigate('/admin/quotations')}>
          <div className="metric-header">
            <span className="metric-title">PENDING APPROVALS</span>
            <svg className="metric-icon text-warning" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
          </div>
          <div className="metric-value text-warning">{pendingApprovals}</div>
          <div className="metric-subtitle">Awaiting manager review</div>
        </div>

        <div className="metric-card" style={{ cursor: 'pointer' }} onClick={() => navigate('/admin/billing')}>
          <div className="metric-header">
            <span className="metric-title">OUTSTANDING RECEIVABLES</span>
            <svg className="metric-icon text-danger" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
            </svg>
          </div>
          <div className="metric-value text-danger">{formatCurrencyInr(outstandingReceivables || 2480000)}</div>
          <div className="metric-subtitle">Uncollected invoices</div>
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '2fr 1fr', gap: 'var(--space-6)' }}>
        
        {/* Analytics Section */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-6)' }}>
          <div className="card">
            <div className="card-header">Revenue Trend (H1 YTD)</div>
            <div className="card-body" style={{ height: '300px', display: 'flex', alignItems: 'flex-end', gap: '1rem', paddingBottom: '2rem', paddingTop: '2rem' }}>
              {chartData.map((data, i) => (
                <div 
                  key={i} 
                  onMouseEnter={() => setHoveredBar(i)}
                  onMouseLeave={() => setHoveredBar(null)}
                  style={{ 
                    flex: 1, 
                    height: `${data.height}%`, 
                    background: hoveredBar === i ? 'var(--primary)' : 'linear-gradient(180deg, var(--primary) 0%, rgba(79, 70, 229, 0.2) 100%)', 
                    borderRadius: '4px 4px 0 0', 
                    position: 'relative', 
                    animation: `slideUp ${0.3 + (i * 0.1)}s ease-out backwards`,
                    cursor: 'pointer',
                    transition: 'all 0.2s ease'
                  }}
                >
                  {hoveredBar === i && (
                    <div style={{
                      position: 'absolute',
                      top: '-40px',
                      left: '50%',
                      transform: 'translateX(-50%)',
                      background: 'var(--surface)',
                      border: '1px solid var(--border)',
                      padding: '0.375rem 0.75rem',
                      borderRadius: '6px',
                      fontSize: '0.875rem',
                      fontWeight: 600,
                      color: 'var(--text-primary)',
                      whiteSpace: 'nowrap',
                      boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
                      zIndex: 10
                    }}>
                      ₹{(data.revenue / 100000).toFixed(1)} Lakhs
                    </div>
                  )}
                  <span style={{ 
                    position: 'absolute', 
                    bottom: '-25px', 
                    left: '50%', 
                    transform: 'translateX(-50%)', 
                    fontSize: '0.75rem', 
                    color: hoveredBar === i ? 'var(--primary)' : 'var(--text-secondary)',
                    fontWeight: hoveredBar === i ? 600 : 400,
                    transition: 'color 0.2s ease, font-weight 0.2s ease'
                  }}>
                    {data.month}
                  </span>
                </div>
              ))}
            </div>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 'var(--space-6)' }}>
            <div className="card">
              <div className="card-header">Quote Conversion</div>
              <div className="card-body">
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.5rem' }}>
                  <span style={{ fontSize: '0.875rem' }}>Approved & Confirmed</span>
                  <strong className="text-success">52%</strong>
                </div>
                <div style={{ width: '100%', height: '8px', backgroundColor: 'var(--surface-secondary)', borderRadius: '4px', marginBottom: '1.5rem' }}>
                  <div style={{ width: '52%', height: '100%', backgroundColor: 'var(--success)', borderRadius: '4px' }}></div>
                </div>

                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.5rem' }}>
                  <span style={{ fontSize: '0.875rem' }}>In Negotiation / Review</span>
                  <strong className="text-warning">33%</strong>
                </div>
                <div style={{ width: '100%', height: '8px', backgroundColor: 'var(--surface-secondary)', borderRadius: '4px', marginBottom: '1.5rem' }}>
                  <div style={{ width: '33%', height: '100%', backgroundColor: 'var(--warning)', borderRadius: '4px' }}></div>
                </div>
                
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.5rem' }}>
                  <span style={{ fontSize: '0.875rem' }}>Rejected / Expired</span>
                  <strong className="text-danger">15%</strong>
                </div>
                <div style={{ width: '100%', height: '8px', backgroundColor: 'var(--surface-secondary)', borderRadius: '4px' }}>
                  <div style={{ width: '15%', height: '100%', backgroundColor: 'var(--danger)', borderRadius: '4px' }}></div>
                </div>
              </div>
            </div>
            
            <div className="card">
              <div className="card-header">Critical System Alerts</div>
              <div className="card-body" style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
                <div style={{ display: 'flex', gap: '1rem', alignItems: 'flex-start' }}>
                  <div style={{ width: '8px', height: '8px', borderRadius: '50%', backgroundColor: 'var(--danger)', marginTop: '6px' }}></div>
                  <div>
                    <strong style={{ display: 'block', fontSize: '0.875rem', marginBottom: '2px' }}>3 products below critical threshold</strong>
                    <span style={{ fontSize: '0.75rem', color: 'var(--text-secondary)' }}>Inventory replenishment required</span>
                  </div>
                </div>
                <div style={{ display: 'flex', gap: '1rem', alignItems: 'flex-start' }}>
                  <div style={{ width: '8px', height: '8px', borderRadius: '50%', backgroundColor: 'var(--warning)', marginTop: '6px' }}></div>
                  <div>
                    <strong style={{ display: 'block', fontSize: '0.875rem', marginBottom: '2px' }}>{pendingApprovals} quotes pending high-margin review</strong>
                    <span style={{ fontSize: '0.75rem', color: 'var(--text-secondary)' }}>Approval rule engine escalation triggered</span>
                  </div>
                </div>
                <div style={{ display: 'flex', gap: '1rem', alignItems: 'flex-start' }}>
                  <div style={{ width: '8px', height: '8px', borderRadius: '50%', backgroundColor: 'var(--brand)', marginTop: '6px' }}></div>
                  <div>
                    <strong style={{ display: 'block', fontSize: '0.875rem', marginBottom: '2px' }}>New Enterprise Customer Onboarded</strong>
                    <span style={{ fontSize: '0.75rem', color: 'var(--text-secondary)' }}>Acme Corp assigned Platinum price list</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Recent Activity Sidebar */}
        <div className="card">
          <div className="card-header">Executive Audit Log</div>
          <div className="card-body" style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem', padding: 'var(--space-6) var(--space-4)' }}>
            
            <div style={{ display: 'flex', gap: '1rem', position: 'relative' }}>
              <div style={{ position: 'absolute', left: '15px', top: '32px', bottom: '-24px', width: '2px', backgroundColor: 'var(--border)' }}></div>
              <div style={{ width: '32px', height: '32px', borderRadius: '50%', backgroundColor: 'var(--primary-light)', color: 'var(--primary)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1, flexShrink: 0 }}>
                <svg style={{ width: '16px', height: '16px' }} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6v6m0 0v6m0-6h6m-6 0H6" /></svg>
              </div>
              <div>
                <p style={{ fontSize: '0.875rem', margin: '0 0 4px 0' }}><strong>Admin</strong> approved quote <strong>Q-2026-004</strong></p>
                <span style={{ fontSize: '0.75rem', color: 'var(--text-tertiary)' }}>10 minutes ago</span>
              </div>
            </div>

            <div style={{ display: 'flex', gap: '1rem', position: 'relative' }}>
              <div style={{ position: 'absolute', left: '15px', top: '32px', bottom: '-24px', width: '2px', backgroundColor: 'var(--border)' }}></div>
              <div style={{ width: '32px', height: '32px', borderRadius: '50%', backgroundColor: 'var(--success-bg)', color: 'var(--success-text)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1, flexShrink: 0 }}>
                <svg style={{ width: '16px', height: '16px' }} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" /></svg>
              </div>
              <div>
                <p style={{ fontSize: '0.875rem', margin: '0 0 4px 0' }}><strong>Finance Manager</strong> marked invoice <strong>INV-904</strong> as Paid</p>
                <span style={{ fontSize: '0.75rem', color: 'var(--text-tertiary)' }}>1 hour ago</span>
              </div>
            </div>

            <div style={{ display: 'flex', gap: '1rem', position: 'relative' }}>
              <div style={{ position: 'absolute', left: '15px', top: '32px', bottom: '-24px', width: '2px', backgroundColor: 'var(--border)' }}></div>
              <div style={{ width: '32px', height: '32px', borderRadius: '50%', backgroundColor: 'var(--warning-bg)', color: 'var(--warning-text)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1, flexShrink: 0 }}>
                <svg style={{ width: '16px', height: '16px' }} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" /></svg>
              </div>
              <div>
                <p style={{ fontSize: '0.875rem', margin: '0 0 4px 0' }}><strong>System</strong> updated inventory for <strong>SKU-SYS-001</strong></p>
                <span style={{ fontSize: '0.75rem', color: 'var(--text-tertiary)' }}>3 hours ago</span>
              </div>
            </div>

            <div style={{ display: 'flex', gap: '1rem' }}>
              <div style={{ width: '32px', height: '32px', borderRadius: '50%', backgroundColor: 'var(--surface-secondary)', color: 'var(--text-secondary)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1, flexShrink: 0 }}>
                <svg style={{ width: '16px', height: '16px' }} fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" /></svg>
              </div>
              <div>
                <p style={{ fontSize: '0.875rem', margin: '0 0 4px 0' }}><strong>Admin</strong> updated <strong>Discount Rules</strong></p>
                <span style={{ fontSize: '0.75rem', color: 'var(--text-tertiary)' }}>Yesterday</span>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  );
}

export default Dashboard;
