# Generated by Django 4.2.30 on 2026-09-05 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sales", "0002_remove_quotation_idx_quote_customer_created_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerNegotiation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("counter_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("customer_notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("COUNTERED", "Countered"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("response_notes", models.TextField(blank=True, default="")),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="negotiations",
                        to="sales.quotation",
                    ),
                ),
            ],
            options={
                "db_table": "customer_negotiations",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
