# Generated by Django 4.2.30 on 2026-09-05 09:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quotation_number",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("customer_id", models.CharField(db_index=True, max_length=128)),
                ("sales_rep_id", models.CharField(db_index=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("SENT", "Sent"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=32,
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("NOT_REQUIRED", "Not Required"),
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="NOT_REQUIRED",
                        max_length=32,
                    ),
                ),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "cost_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "margin_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "margin_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "blended_risk_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Quotation",
                "verbose_name_plural": "Quotations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuotationVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("snapshot_data", models.JSONField()),
                (
                    "changed_by",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("change_reason", models.TextField(blank=True, default="")),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="sales.quotation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quotation Version",
                "verbose_name_plural": "Quotation Versions",
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="QuotationItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_id", models.CharField(db_index=True, max_length=128)),
                ("product_name", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "tax_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "cost_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "cost_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "margin_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "margin_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.quotation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quotation Item",
                "verbose_name_plural": "Quotation Items",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(
                fields=["status", "-created_at"], name="idx_quote_status_created"
            ),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(
                fields=["customer_id", "-created_at"], name="idx_quote_customer_created"
            ),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(
                fields=["sales_rep_id", "-created_at"], name="idx_quote_rep_created"
            ),
        ),
        migrations.AddConstraint(
            model_name="quotation",
            constraint=models.CheckConstraint(
                check=models.Q(("subtotal__gte", 0)),
                name="quotation_subtotal_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="quotation",
            constraint=models.CheckConstraint(
                check=models.Q(("total_amount__gte", 0)),
                name="quotation_total_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="quotationversion",
            constraint=models.UniqueConstraint(
                fields=("quotation", "version_number"),
                name="unique_quotation_version_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="quotationitem",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gt", 0)), name="item_quantity_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="quotationitem",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("discount_percent__gte", 0), ("discount_percent__lte", 100)
                ),
                name="item_discount_pct_range",
            ),
        ),
    ]
