# Generated by Django 4.2.30 on 2026-09-05 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_category_pricelist_product_cost_price_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "customer",
            "0002_customertier_customer_address_customer_customer_code_and_more",
        ),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="quotation",
            name="idx_quote_customer_created",
        ),
        migrations.RemoveIndex(
            model_name="quotation",
            name="idx_quote_rep_created",
        ),
        migrations.RemoveField(
            model_name="quotation",
            name="customer_id",
        ),
        migrations.RemoveField(
            model_name="quotation",
            name="sales_rep_id",
        ),
        migrations.RemoveField(
            model_name="quotationitem",
            name="product_id",
        ),
        migrations.AddField(
            model_name="quotation",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotations",
                to="customer.customer",
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="sales_rep",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotation_items",
                to="product.product",
            ),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotation_items",
                to="product.productvariant",
            ),
        ),
        migrations.AlterField(
            model_name="quotationversion",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotation_versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
