# Generated by Django 4.2.30 on 2026-09-05 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_category_pricelist_product_cost_price_and_more"),
        ("sales", "0002_remove_quotation_idx_quote_customer_created_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "customer",
            "0002_customertier_customer_address_customer_customer_code_and_more",
        ),
        ("discount", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("sequence", models.PositiveIntegerField(default=1)),
                (
                    "required_role",
                    models.CharField(default="SALES_MANAGER", max_length=50),
                ),
            ],
            options={
                "db_table": "approval_levels",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("min_risk_score", models.IntegerField(default=0)),
                ("max_risk_score", models.IntegerField(default=100)),
            ],
            options={
                "db_table": "approval_rules",
            },
        ),
        migrations.CreateModel(
            name="ApprovalRuleStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField(default=1)),
                (
                    "approval_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discount.approvallevel",
                    ),
                ),
                (
                    "approval_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="discount.approvalrule",
                    ),
                ),
            ],
            options={
                "db_table": "approval_rule_steps",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="DiscountRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_discount_percent",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
                ),
                (
                    "manager_threshold_percent",
                    models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
                ),
                (
                    "finance_threshold_percent",
                    models.DecimalField(decimal_places=2, default=25.0, max_digits=5),
                ),
                (
                    "min_margin_percent",
                    models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discount_rules",
                        to="product.category",
                    ),
                ),
                (
                    "customer_tier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discount_rules",
                        to="customer.customertier",
                    ),
                ),
            ],
            options={
                "db_table": "discount_rules",
                "unique_together": {("customer_tier", "category")},
            },
        ),
        migrations.CreateModel(
            name="QuotationApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("RETURNED", "Returned"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField(blank=True, default="")),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approval_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="discount.approvallevel",
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="sales.quotation",
                    ),
                ),
            ],
            options={
                "db_table": "quotation_approvals",
                "ordering": ["sequence"],
            },
        ),
        migrations.DeleteModel(
            name="Discount",
        ),
    ]
