# Generated by Django 4.2.30 on 2026-09-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discount", "0002_approvallevel_approvalrule_approvalrulestep_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalrule",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="discountrule",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="discountrule",
            name="name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
